### ISSUE TITLE
If you click the logo when using twitter, you can skip the email process

### ISSUE THREAD

**Issue by henry2992** [henry2992/AprendeRails.com#9]

**Comment by ghost** [comment]
Updated ./app/views/layouts/application.html.erb and _header partial to check for email. If no email is present, will display the finish signup screen until email is entered. Additional validations will be needed in the controllers to ensure the user does not enter a url to skip the email process. Something like this:

if current_user.email.split('@')[1] == 'change-me.com'
    redirect_to finish_signup_path(current_user)
end

> > will open separate issue for this
